tasks:
  - name: O1-1
    label: O1
    timeLimit: 10
    events:
      - type: gate
        label: Gate-1
        location: [ [ 4.69, 3.49, 0.35 ], [ 1.79, 3.49, 0.35 ] ]
      - type: gate
        label: Gate-2
        location: [ [ 4.69, 7.305, 0.35 ], [ 1.79, 7.305, 0.35 ] ]
